// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"webapi/pkg/config"
	"webapi/pkg/store"
)

// Injectors from wire.go:

func Initialize(dbConfig *config.DbConfig) (*store.DbStorage, error) {
	dbStorage, err := store.NewDbStorage(dbConfig)
	if err != nil {
		return nil, err
	}
	return dbStorage, nil
}
