version: '3.3'
services:
  # OpenTelemetry Collector
  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.70.0
    command: --config=/etc/otel-collector-config.yaml
    container_name: otel_collector
    volumes:
      - ./confs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./confs/server.crt:/etc/tls/server.crt
      - ./confs/server.key:/etc/tls/server.key
      - ./confs/rootCA.crt:/etc/tls/rootCA.crt
    ports:
      - "4317:4317" # OTLP over gRPC receiver
      - "9464:9464" # Prometheus exporter
    depends_on:
      - jaeger
      - prometheus
    networks:
      - monitor_network

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.41.0
    container_name: jaeger
    ports:
      - "14250:14250" # Collector gRPC
      - "16686:16686" # Web HTTP
    networks:
      - monitor_network

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.42.0
    command:
      - --config.file=/etc/prometheus/prometheus-config.yaml
    container_name: prometheus
    volumes:
      - ./confs/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    ports:
      - "9090:9090"
    networks:
      - monitor_network

  server:
    image: smartpcr/monitoring-server:dev
    container_name: server
    ports:
      - "5555:5555"
    depends_on:
      - otel_collector
    networks:
      - monitor_network

  client:
    image: smartpcr/monitoring-client:dev
    container_name: client
    depends_on:
      - server
    networks:
      - monitor_network

networks:
  monitor_network: